module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/functions/',
    '/functions-catalog/',
    '\\.emulator\\.test\\.[jt]sx?$',
  ],
  collectCoverageFrom: [
    'core/**/*.{ts,tsx}',
    'features/**/*.{ts,tsx}',
    'adapters/**/*.{ts,tsx}',
    'theme/**/*.{ts,tsx}',
    'presentation/ui/**/*.{ts,tsx}',
    'presentation/patterns/details/**/*.{ts,tsx}',
    'presentation/patterns/lists/**/*.{ts,tsx}',
    'presentation/patterns/catalog/**/*.{ts,tsx}',
    'presentation/patterns/roles/**/*.{ts,tsx}',
    'presentation/forms/**/*.{ts,tsx}',
    'presentation/auth/**/*.{ts,tsx}',
    'presentation/screens/settings/administration/components/**/*.{ts,tsx}',
    'presentation/screens/community/alerts/components/AlertListItem.tsx',
    'presentation/screens/catalog/components/CatalogToolbar.tsx',
    'presentation/screens/stations/components/StationListItem.tsx',
    '!**/*.test.{ts,tsx}',
    '!**/index.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'json-summary'],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 80,
      functions: 80,
      lines: 80,
    },
  },
};
