import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

const buttonStyles = StyleSheet.create({
  /** General purpose Buttons */
  button: {
    width: width * 0.85,
    backgroundColor: '#333',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    padding: height * 0.006,
    borderRadius: width * 0.015,
  },
  rowButton: {
    width: 'auto',
    minWidth: width * 0.2,
    maxWidth: width * 0.3,
    height: height * 0.035,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: width * 0.02,
    paddingVertical: height * 0.005,
    marginHorizontal: width * 0.0125,
    marginVertical: height * 0.01,
    borderRadius: width * 0.02,
    fontSize: width * 0.04,
    textAlign: 'center',
  },
  rowButton2: {
    width: 'auto',
    minWidth: width * 0.16,
    maxWidth: width * 0.3,
    height: height * 0.05,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: width * 0.02,
    paddingVertical: height * 0.005,
    marginHorizontal: width * 0.0125,
    marginVertical: height * 0.01,
    borderRadius: width * 0.05,
    backgroundColor: '#e0e0e0',
    fontSize: width * 0.04,
    textAlign: 'center',
  },
  bigButton: {
    width: width * 0.9,
    height: height * 0.06,
    backgroundColor: '#333',
    paddingVertical: height * 0.015,
    paddingHorizontal: 0,
    borderRadius: width * 0.08,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    display: 'flex',
    margin: height * 0.006,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  mediumButton: {
    width: width * 0.7,
    height: height * 0.06,
    backgroundColor: '#333',
    paddingVertical: height * 0.015,
    paddingHorizontal: 0,
    borderRadius: width * 0.08,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    display: 'flex',
    margin: height * 0.006,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  bigDeleteButton: {
    width: width * 0.9,
    height: height * 0.06,
    backgroundColor: 'red',
    paddingVertical: height * 0.015,
    paddingHorizontal: width * 0.05,
    borderRadius: width * 0.08,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    margin: height * 0.006,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  /** Corner buttons  */
  smallButtonTopRight: {
    width: width * 0.1,
    height: height * 0.035,
    position: 'absolute',
    top: height * 0.0125,
    right: width * 0.025,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    margin: 0,
    paddingHorizontal: height * 0.005,
    paddingVertical: height * 0.005,
    borderRadius: width * 0.015,
    zIndex: 10,
  },
  smallButtonTopLeft: {
    width: width * 0.09,
    height: width * 0.09,
    position: 'absolute',
    top: height * 0.02,
    left: width * 0.02,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    padding: height * 0.005,
    borderRadius: width * 0.015,
    zIndex: 10,
  },
  /** Special Case Buttons */
  imageButton: {
    backgroundColor: '#333',
    borderRadius: width * 0.025,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  imageDeleteButton: {
    width: width * 0.15,
    height: height * 0.035,
    backgroundColor: 'red',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    padding: height * 0.006,
    borderRadius: width * 0.015,
  },
  cameraButton: {
    width: width * 0.18,
    height: width * 0.18,
    borderRadius: width * 0.09,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
    paddingVertical: height * 0.01,
    paddingHorizontal: width * 0.05,
  },
  reportButton: {
    position: 'absolute',
    width: width * 0.25,
    height: height * 0.062,
    bottom: height * 0.025,
    alignSelf: 'center',
    backgroundColor: '#007bff',
    paddingVertical: height * 0.012,
    paddingHorizontal: width * 0.025,
    borderRadius: width * 0.035,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
  },
  activeButton: {
    backgroundColor: '#007bff',
  },
});

export { buttonStyles };
