//Container styles
import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');
const vw = width / 100;
const vh = height / 100;

const containerStyles = StyleSheet.create({
  /** Screen Wrappers  */
  wrapper: {
    flex: 1,
    backgroundColor: '#FAFAFA',
    paddingTop: Platform.select({
      ios: vh * 10, // avoid iOS Dynamic Island
      default: 0,
    }),
  },
  imageWrapper: {
    flexDirection: 'column',
    position: 'relative',
    margin: vw * 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: vw * 1.5,
  },
  scrollView: {
    paddingTop: vh,
    paddingBottom: vh * 20,
  },
  scrollViewPadded: {
    paddingTop: vh * 5,
    paddingBottom: vh * 20,
  },
  scrollViewCenter: {
    paddingTop: vh * 2,
    paddingBottom: vh * 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollViewCenterPadded: {
    paddingTop: vh * 2,
    paddingBottom: vh * 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  /** Cards */
  card: {
    flexDirection: 'column',
    alignSelf: 'center',
    width: vw * 95,
    height: 'auto',
    padding: vw * 5,
    backgroundColor: '#fff',
    borderRadius: vw * 4,
    marginHorizontal: vw * 3,
    marginBottom: vh * 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  shadedCard: {
    width: vw * 80,
    backgroundColor: '#f9f9f9',
    padding: vw * 5,
    borderRadius: vw * 2.5,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    margin: vw * 2,
  },
  stationCard: {
    width: vw * 95,
    padding: vw * 4,
    backgroundColor: '#fff',
    borderRadius: vw * 3,
    marginHorizontal: vw * 3,
    marginBottom: vh * 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionCard: {
    padding: vw * 2.5,
    backgroundColor: '#F0F4F8',
    borderRadius: vw * 3,
  },
  verticalCard: {
    flexDirection: 'column',
    alignSelf: 'center',
  },
  /** Input Containers */
  inputContainer: {
    padding: Platform.select({
      ios: vw * 2.5,
      default: 0,
    }),
    width: width * 0.85,
    height: vh * 5,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: vw * 1.5,
    marginBottom: vh * 2,
    paddingHorizontal: vw * 2.5,
    backgroundColor: '#fff',
    color: '#000',
    justifyContent: 'center',
    textAlign: 'left',
    flex: 1,
  },
  smallInputContainer: {
    padding: Platform.select({
      ios: vw * 2.5,
      default: 0,
    }),
    width: width * 0.7,
    height: vh * 5,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: vw * 1.5,
    marginBottom: vh * 2,
    paddingHorizontal: vw * 2.5,
    backgroundColor: '#fff',
    color: '#000',
    justifyContent: 'center',
    textAlign: 'left',
    flex: 1,
  },
  descInputContainer: {
    padding: vw * 2.5,
    width: width * 0.85,
    height: vh * 10,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: vw * 1.5,
    marginBottom: vh * 2,
    paddingHorizontal: vw * 2.5,
    backgroundColor: '#fff',
    color: '#000',
    textAlign: 'left',
  },
  dateInputContainer: {
    height: vh * 8,
    width: width * 0.85,
    padding: vw * 2.5,
    flexDirection: 'row',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: vw * 1.5,
    marginBottom: vh * 2,
    paddingHorizontal: vw * 2.5,
    backgroundColor: '#fff',
    color: '#000',
  },
  /** Text Containers */
  listDetailsContainer: {
    flexDirection: 'column',
    width: width,
    height: vh * 25,
    flex: 1,
    justifyContent: 'flex-start',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  columnContainer: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footer: {
    marginTop: vh * 2,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: vh * 1,
  },
  rowStack: {
    flexDirection: 'column',
    padding: vw * 1.5,
    gap: vw * 2,
  },
  closeRowStack: {
    flexDirection: 'column',
    padding: vw * 1.5,
  },
  /** Image Containers */
  imageLarge: {
    width: vw * 70,
    height: vh * 35,
    borderRadius: vw * 5.5,
    marginBottom: vh * 2,
    alignSelf: 'center',
    overflow: 'hidden',
    justifyContent: 'center',
  },
  imageMain: {
    width: width * 0.85,
    height: vh * 25,
    borderRadius: vw * 5.5,
    marginBottom: vh * 2,
    alignSelf: 'center',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listImage: {
    width: width * 0.8,
    height: vh * 20,
    borderRadius: vw * 5.5,
    marginBottom: vh * 2,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  cardImage: {
    width: vw * 40,
    height: vw * 40,
    borderRadius: vw * 3,
    marginRight: vw * 3,
    justifyContent: 'center',
  },
  extraPic: {
    width: vw * 25,
    height: vw * 25,
    borderRadius: vw * 3,
    resizeMode: 'cover',
  },
  extraPicsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  /** Misc. elements Containers */
  cameraContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: vw * 2.5,
  },
  datePickerContainer: {
    backgroundColor: '#fff',
    flex: 1,
    justifyContent: 'center',
  },
  buttonGroup: {
    width: width,
    height: 'auto',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    flexWrap: 'nowrap',
  },
  buttonGroup2: {
    width: width * 0.85,
    height: 'auto',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flexWrap: 'nowrap',
  },
  mapContainer: {
    height: vh * 25,
    width: width * 0.85,
    borderRadius: vw * 3,
    marginBottom: vh * 1.5,
    overflow: 'hidden',
  },
  snackbarContainer: {
    position: 'absolute',
    top: vh * 12,
    left: vw * 3,
    right: vw * 3,
    zIndex: 1000,
  },
  snackbar: {
    width: width * 0.9,
    height: vh * 5,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    color: 'white',
    borderRadius: vw * 1.5,
  },
});
export { containerStyles };
