//Button styles
import { StyleSheet } from 'react-native';

const buttonStyles = StyleSheet.create({
  /** General purpose Buttons */
  button: {
    width:'100%',
    backgroundColor: '#333',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 5,
  },
  deleteButton: {
    width:'100%',
    backgroundColor: 'red',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 5,
  },
  rowButton: {
    width:'auto',
    minWidth: '30%',
    maxWidth: '40%',
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
    paddingVertical: 2,
    marginHorizontal: 5,
    marginVertical: 8,
    borderRadius: 8,
    fontSize: 16,
    textAlign: 'center',
  },
  rowButton2: {
    width:'auto',
    minWidth: '16%',
    maxWidth: '30%',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginHorizontal: 5,
    marginVertical: 8,
    borderRadius: 20,
    backgroundColor: '#e0e0e0',
    fontSize: 16,
    textAlign: 'center',
  },
  bigButton: {
    width:'90%',
    height:'6%',
    backgroundColor: '#333',
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderRadius: 30, 
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    display: 'flex',
    margin:5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    
  },
  bigDeleteButton: {
    width:'90%',
    height:'6%',
    backgroundColor: 'red',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30, 
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    margin: 5, 
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  /** Corner buttons  */
  smallButtonTopRight: {
    width: 40,
    height: 25,
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    padding: 5,
    borderRadius: 5,
    zIndex: 10,
  },
  smallButtonTopLeft: {
    width: 35,
    height:35,
    position: 'absolute',
    top: '2%',
    left: '2%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    padding: 5,
    borderRadius: 5,
    zIndex: 10,
  },
  /** Special Case Buttons */
  imageButton: {
    backgroundColor: '#333',
    borderRadius: 10,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  imageDeleteButton: {
    width:60,
    height:30,
    backgroundColor: 'red',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 5,
  },
  cameraButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  reportButton: {
    position: 'absolute',
    width:'25%',
    height:'6%',
    bottom: 20,
    alignSelf: 'center',
    backgroundColor: '#007bff',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
  },
  activeButton: {
    backgroundColor: '#007bff'
  },
});
export { buttonStyles };
