//Button styles
import { StyleSheet } from 'react-native';

const buttonStyles = StyleSheet.create({
  /** Main Buttons */
  button: {
    width:'100%',
    backgroundColor: '#333',
    padding:5,
    borderRadius: 5,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  deleteButton: {
    width:'100%',
    backgroundColor: 'red',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 5,
  },
  bigButton: {
    width:'90%',
    height:'6%',
    backgroundColor: '#333',
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderRadius: 30, 
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    display: 'flex',
    margin:5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    
  },
  bigDeleteButton: {
    width:'90%',
    height:'6%',
    backgroundColor: 'red',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30, 
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    margin: 5, 
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  /** Special Case Buttons */
  dateButton: {
    backgroundColor: '#0b6623',
    padding: 5,
    borderRadius: 5,
    marginTop: 5,
  },
  blockButton: {
    width:'30%',
    backgroundColor: 'red',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 5,
  },
  promoteButton: {
    width:'30%',
    backgroundColor: 'green',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 5,
  },
  demoteButton: {
    width:'30%',
    backgroundColor: 'blue',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    padding: 5,
    borderRadius: 5,
  },
  smallButtonTopRight: {
    width: 35,
    height: 25,
    position: 'absolute',
    top: '10%',
    right: '3%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    padding: 5,
    borderRadius: 5,
    zIndex: 10,
  },
  smallButtonTopLeft: {
    width: 35,
    height:35,
    position: 'absolute',
    top: '2%',
    left: '2%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    padding: 5,
    borderRadius: 5,
    zIndex: 10,
  },
  imageButton: {
    backgroundColor: '#333',
    borderRadius: 10,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  cameraButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  reportButton: {
    position: 'absolute',
    width:'25%',
    height:'6%',
    bottom: 20,
    alignSelf: 'center',
    backgroundColor: '#007bff',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.5,
  },
  filterButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginHorizontal: 5,
    marginVertical: 0,
    borderRadius: 20,
    backgroundColor: '#e0e0e0',
  },
  activeButton: {
    backgroundColor: '#007bff'
  },
  
});
export { buttonStyles };
