//Container styles
import { Platform, StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const IMAGE_WIDTH = SCREEN_WIDTH - 32; // leaving 16px padding on both sides

const containerStyles = StyleSheet.create({
  /** Screen Wrappers  */
  wrapper: {
    flex: 1,
    backgroundColor: '#FAFAFA',
    paddingTop: '10%',
  },
  imageWrapper: {
    flexDirection: "column",
    position: 'relative',
    margin: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap:5
  },
  scrollView: {
    paddingTop: 20, 
    paddingBottom: '40%' 
  },
  scrollViewCenter: {
    paddingTop: 20, 
    paddingBottom: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  /** Cards */
  card: {
    alignSelf:'center',
    width:'95%',
    padding: '5%',
    backgroundColor: '#fff',
    borderRadius: '4%',
    marginHorizontal: '3%',
    marginBottom: '5%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  shadedCard: {
    width: '80%',
    backgroundColor: '#f9f9f9',
    padding: 20,
    borderRadius: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    margin:10,
  },
  stationCard: {
    alignSelf:'center',
    width:'95%',
    flexDirection: 'row',
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginHorizontal: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  sectionCard: {
    padding: 10,
    backgroundColor: '#F0F4F8',
    borderRadius: 12,
  },
  verticalCard: {
    flexDirection: "column",
    alignSelf: "center",
  },
  /** Input Containers */
  inputContainer: {
    padding:10,
    width: '100%',
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 15,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    color: '#000',
    justifyContent: 'center',
    textAlign: 'left',
    flex: 1,
  },
  descInputContainer: {
    padding:10,
    width: '100%',
    height: 80,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 15,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    color: '#000',
    textAlign: 'left',
  },
  dateInputContainer: {
    height: 60,
    width: '100%',
    padding:10,
    flexDirection: 'row', 
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 15,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
    color: '#000',
  },
  /** Text Containers */
  listDetailsContainer: {
    flexDirection: 'column',
    paddingLeft: '2%',
    width: '100%',
    height: '20%',
    flex: 1,
    justifyContent: 'flex-start',
  },
  stationDetailsContainer: {
    flexDirection: 'column',
    paddingLeft: '25%',
    width: 150,
    hieght: 150,
    flex: 1,
    justifyContent: 'space-between',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footer: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 10,
  },
  rowStack: {
    flexDirection: 'column',
    padding:5,
  },
  /** Image Containers */
  imageLarge: {
    width: '80%',
    height: '80%',
    borderRadius: 22,
    marginBottom: 16,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  imageMain: {
    width: '100%',
    height: 200,
    borderRadius: 22,
    marginBottom: 16,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  cardImage: {
    width: 150,
    height: 150,
    borderRadius: 12,
    marginRight: 16,
  },
  extraPic: {
    width: 100,
    height: 100,
    borderRadius: 12,
    resizeMode: 'cover',
  },
  extraPicsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  /** Misc. elements Containers */
  cameraContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  datePickerContainer: {
    backgroundColor: '#fff',
    flex: 1,
    justifyContent: 'center',
  },
  buttonGroup: {
    width: '100%',
    height: 'auto',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    flexWrap: 'nowrap'
  },
  buttonGroup2: {
    width: '100%',
    height: 'auto',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'nowrap',
    justifyContent: 'space-evenly',
  },
  mapContainer: {
    height: 200,
    width: '100%',
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
  },
  snackbarContainer: {
    position: 'absolute',
    top: '15%',
    left: '3%',
    right: '3%',
    zIndex: 1000,
  },
  snackbar: {
    width: '100%',
    height: '20%',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    color: 'white',
    borderRadius: 5,
  },
});
export { containerStyles };